### ISSUE TITLE
Can't find user containers after upgrade to Rancher 1.2.0

### ISSUE THREAD

**Issue by emcniece** [Munsio/docker-letsencrypt-nginx-proxy-companion#11]
This might be better suited for https://github.com/jwilder/docker-gen but maybe you've hit this before. Docker-gen isn't finding any of my userland containers - it only sees the Rancher containers.

To test this, I'm running a block in `nginx.tmpl`:

```yml
# TEST START:
{{ range $host, $containers := groupBy $ "ID" }}
  # Host: {{ $host }}
  {{ range $container := $containers }}
  # {{ $container }}
  {{ end }}

{{ end }}
# TEST END
```

Does this container need to be run on a network setting other than "managed"?

**Comment by emcniece** [comment]
Ok, this ended up being an entirely different problem. I added a second Rancher host around the same time as the Rancher 1.2 upgrade, and the missing containers were being added to the other host. 

Docker-gen doesn't seem to work with service discovery across Rancher Cattle organizations - it works with Docker Swarm (and maybe Kubernetes?) though. Not really sure what it'll take to get docker-gen to work in this use case.

**Comment by Munsio** [comment]
Thats one of the problems of docker-gen and why i want to create a new repo using https://github.com/janeczku/go-rancher-gen

But as the current state it doesn't seems to support sighubs so even if we use the rancher metadata service which we should, we don't have the ability to restart the other containers except if we bundle them which i would avoid.

Also the problem with multiple hosts is something which i doesn't check if it is possible cause i didn't need it in the past.

**Comment by emcniece** [comment]
Aha... https://github.com/janeczku/go-rancher-gen looks promising! Do you have a branch for migration, or are you going to create a new repo?

**Comment by Munsio** [comment]
i think it is going into a new repo cause JrCs which this repo here is based off also uses the docker-gen to create letsencrypt things.

**Comment by emcniece** [comment]
Well, let me know when you get started - I'm happy to contribute and test 😄
