### ISSUE TITLE
Error in generating new ssl-certs

### ISSUE THREAD

**Issue by Munsio** [Munsio/docker-letsencrypt-nginx-proxy-companion#12]
Due to changes at the letsencrypt api the simp_le tool doesn't work anymore, however the original programmer is absent so we have to switch to another tool instead - maybe https://github.com/Neilpang/acme.sh it is written in pure shell so for me i like it more then the python thingy.

Or should we fix this in the new repo? @emcniece

**Comment by Munsio** [comment]
however - currently it isn't possible to generate new certificates with this repo - such a f** crap

**Comment by Munsio** [comment]
fixed the problem with commit: ce71df9561fe73f60ede2d6065eeec36e1e17695

**Comment by emcniece** [comment]
A pure shell implementation might be a better idea - it would certainly help slim down the Docker image if we don't have to install Python.

@Munsio I need a new version of this asap, and this weekend is wide open. Let's get rolling on the new project!
