### ISSUE TITLE
Check docker-gen nginx.tmpl on startup

### ISSUE THREAD

**Issue by Munsio** [Munsio/docker-letsencrypt-nginx-proxy-companion#2]
Currently on start up of the container in the rancher.sh we fetch the live nginx.tmpl and store it.

In the future we should check on each startup if there is a new version of that file on the remote host and overwrite the existing one if needed.

Maybe we add also an environment var to turn this feature on/off

**Comment by emcniece** [comment]
I'm currently working on a [Rancher](http://rancher.com/) implementation of this which can be found [over here](https://github.com/emcniece/rancher-catalog). It's not fully functional yet, and this is one of the bugs I'm fighting with.

I see that your fork is less stale than https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion so I would like to update the [docker-compose.yml](https://github.com/emcniece/rancher-catalog/blob/master/templates/letsencrypt-nginx-proxy/0/docker-compose.yml) to reference your image. Are you planning on publishing this image to Docker Hub?

Anyway, `entrypoint.sh` is probably the best place for the `nginx.tmpl` file check - would you agree?

**Comment by Munsio** [comment]
Hi emcniece,

There is already an existing rancher-catalog entry for nginx+letsencrypt without dns-bindings you can find the repo under [Catalog-Entry](https://github.com/Munsio/rancher-cattle-nginx-letsencrypt). Its very simple to use just add the repository to your custom catalog entries under Admin->Settings 
![image](https://cloud.githubusercontent.com/assets/646513/20699516/04fdbc0e-b608-11e6-881b-3c60c3a5d794.png)

I would appreciate it if you use this entry and give some feedback about what you are missing or what could be improved.

And to your question about docker-hub - yes you can find the automated build [here](https://hub.docker.com/r/munsio/rancher-letsencrypt-nginx-proxy-companion/)

**Comment by emcniece** [comment]
Great, thank you!

**Comment by Munsio** [comment]
Cause of Rancher 1.2 this issue is obsolete
