### ISSUE TITLE
Rancher v1. 2

### ISSUE THREAD

**Issue by adi90x** [Munsio/docker-letsencrypt-nginx-proxy-companion#4]
Hello, 
I am not 100% sure of how this fork is working for rancher,  is it possible to have more info? 
Regards,

**Comment by emcniece** [comment]
I'm using it successfully within several 1.2.0-preX-rcX versions as well as the full 1.2.0 build. The full 1.2.0 version has some networking problems however - the latest fully-working version I have tested is Rancher 1.2.0-pre4-rc6.

**Comment by Munsio** [comment]
I'm currently using it with the 1.2.0 release of rancher without any problems.

@emcniece: the problems regarding network (ipsec container i think) are common problems with the 1.2.0 build im struggling too. But for this there is nothing i can do

**Comment by Munsio** [comment]
okay after i fixed the problems with the ipsec container i ran into the issue that docker-gen can't get the ip or port of an container matching the environment vars

**Comment by adi90x** [comment]
Seems to be link to the new way rancher setup network it's wrote in release
note that container is won't show in Docker inspect, hence no way for
docker-gen to get it

Le 5 déc. 2016 4:11 PM, "Martin Treml" <notifications@github.com> a écrit :

okay after i fixed the problems with the ipsec container i ran into the
issue that docker-gen can't get the ip or port of an container matching the
environment vars

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/issues/4#issuecomment-264878840>,
or mute the thread

**Comment by Munsio** [comment]
@adi90x thats true.
The ipsec container hides the ip address of the container. When i got home i will try to modify the template to use the "io.rancher.container.ip" label if all other network resources are empty.

**Comment by adi90x** [comment]
Would be nice! I tried some stuff but I m not really good in Go template!

**Comment by Munsio** [comment]
@adi90x @emcniece - i updated the repo and triggered a new build please use "docker pull munsio/rancher-letsencrypt-nginx-proxy-companion" to update your image.

If this doesn't work please delete the service and install it new from the catalog.

Also there is currently a bug i cannot fix so you have to provide an VIRTUAL_PORT environment var to each container who should be handled by the proxy

**Comment by adi90x** [comment]
I will try tomorrow,  do I have to launch it as sidekick with nginx as a
principal?  Or it replace jwilder/nginx?

**Comment by emcniece** [comment]
https://github.com/jwilder/docker-gen/issues/77

**Comment by Munsio** [comment]
@adi90x i use it with my rancher-catalog entry - its a finished 3 container set as described in the readme.

@emcniece is the reference for me or for the others?

**Comment by emcniece** [comment]
Sorry, wrong repo! That link is marginally relevant as docker-gen needs to move to tags for some things. Feel free to disregard.

**Comment by adi90x** [comment]
Just a small point : you mount `/etc/nginx/docker-gen/` to  use /etc/nginx/docker-gen/docker-gen.cfg, what is this file docker-gen.cfg ?

**Comment by Munsio** [comment]
You can find the docker-gen.cfg here: https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/blob/master/app/docker-gen.cfg

It is the configuration file for docker-gen which use instead of the direct command.
Rancher names the container in different ways so in the /app/rancher.sh i call ranchers metadata service to get the correct container name and write it in this config file so docker-gen nows on which container it should send the sighub

**Comment by adi90x** [comment]
Not sure it work as expected as I still have

`12/6/2016 9:28:47 AM2016/12/06 08:28:47 Sending container 'r-front_nginx_1' signal '1'
12/6/2016 9:28:47 AM2016/12/06 08:28:47 Error sending signal to container: No such container: r-front_nginx_1`

Seems that it don't get the last part of the container name

**Comment by adi90x** [comment]
Seems that we need to add the first part of the container uuid at the end of the container name .
`curl -s rancher-metadata/latest/self/stack/services/0/containers/0/uuid`
Or something like that should do the trick !

**Comment by Munsio** [comment]
thats strange the name of the container with docker ps is different from the one inside rancher.
I will have a look later today to solve this issue.

**Comment by adi90x** [comment]
yes in rancher they display the name , but in docker the add the first part of uuid at the end !

**Comment by adi90x** [comment]
Maybe easier to fork jwilder/nginx-proxy and change nginx.tmpl to add rancher managed network no ? ( I may try to do something this week end )

**Comment by adi90x** [comment]
Or there could be something doable with [https://github.com/janeczku/go-rancher-gen](url)

**Comment by Munsio** [comment]
@adi90x in the latest version from yesterday i already fixed the problem with the managed network.

The problem with the container name is a new one i had to fix this evening - but i have an idea on how to fix it.

Also this go-rancher-gen seems very interesting the only thing i have to figure out is how we can send an sighub to an container if it isn't bundled with the base image

**Comment by adi90x** [comment]
to solve the probleme of the container name , just need to pull the uuid of the containers nginx , split it by "-" and take the first part.
Regarding go-rancher-gen , I guess it could be possible to bundle it with nginx , in the same image ( like what is done for nginx-proxy from jwilder)  and therefore no probleme to get container name , just need to send sighup inside the container ...

**Comment by Munsio** [comment]
@adi90x: i solved the problem with the last new build.
Be sure to run docker pull with my image and then upgrade the service to recreate the container.

If you want to be sure if it has worked check the /volumes/proxyDockerGen/_data/docker-gen.cfg file. Under the section [config.NotifyContainers] should be an container id instead of the container name

**Comment by adi90x** [comment]
Hello, 

I just push a new image based on jwilder/nginx-proxy but setup with rancher-gen in order to bypass all the problem.
Do not hesitate to report any issue ! 
[adi90x/rancher-active-proxy](https://github.com/adi90x/rancher-active-proxy)
Automated build available : [DockerHub](https://hub.docker.com/r/adi90x/rancher-active-proxy/)
Regards,

**Comment by Munsio** [comment]
There are no problems since Dec 6, 2016 with this repository. And bundling the rancher-gen with nginx is an option we want to avoid at all costs.
