### ISSUE TITLE
nginx.tmpl rewritten each time stack is recreated

### ISSUE THREAD

**Issue by emcniece** [Munsio/docker-letsencrypt-nginx-proxy-companion#9]
As I test various configurations and versions of this container (as a part of [this catalog](https://github.com/emcniece/rancher-catalog/tree/master/templates/letsencrypt-nginx-proxy)) I am deleting and re-adding the stack within Rancher. This catalog binds a few volumes, one of which is `/etc/nginx/conf.d`, and each time the stack is rebuilt these files get re-copied which clears any config customizations that I have made. 

[rancher.sh ](https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/blob/master/app/rancher.sh#L12) handles `nginx.tmpl` specifically. This is important behaviour, especially as we have found during the Rancher 1.2.0 upgrade there are times when certain files should be force updated so that they actually work in the environment.

The `nginx.tmpl` could be specified within [docker-gen.cfg](https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/blob/master/app/docker-gen.cfg), but to make this config persist between recreations I will need to 1) add a new volume, and 2) update `docker-gen.cfg` on each recreation.

What do you think about adding a file existence check to `nginx.tmpl` before the copy? Should I just stick with re-resetting my template each time?

**Comment by Munsio** [comment]
I know the problem and for me it is okay to check if the file already exists but especially such checks are causing problems for people during upgrades - so how should we deal with this?

At least the docker-gen.cfg has to be overwritten each time the container spins up to have the correct docker id for the sighub. maybe we can solve this problem in the future after i set up my new ideas with this container

**Comment by emcniece** [comment]
Agreed that `docker-gen.cfg` needs to be overwritten, though hopefully in the near future we will be able to use tags instead of ID or name ;)

If the biggest problem is handling version updates, maybe we can give users clues or hints about that. 

Brainstorm:

- Copy newer `nginx.tmpl` file versions to `nginx.tmpl-$DOCKER_VER` and still use `nginx.tmpl` as the real template
- Print comments about versions in the container STDOUT
- Output a warning in the template file itself?

These ideas might not be worth the effort, not sure.
